{
 "title": "Temphub - Overview",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Temperature (°C)",
   "type": "stat",
   "gridPos": { "h": 18, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "off_chip_temp{}" }
   ]
  },
  {
   "title": "Temperature Timeseries (°C)",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 16, "x": 8, "y": 0 },
   "targets": [
    { "expr": "off_chip_temp{}" }
   ]
  },
  {
   "title": "Humidity (%)",
   "type": "stat",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "on_chip_humidity{}" }
   ]
  },
  {
   "title": "Brightness (Lux)",
   "type": "stat",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "on_chip_brightness{}" }
   ]
  },
  {
   "title": "Pressure (Pascal)",
   "type": "stat",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "barometer_pressure{}" }
   ]
  }
 ]
}