global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'temp_hub'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:8080']

remote_write:
- url: https://zzz.vvv/api/prom/push
  basic_auth:
    username: xxx
    password: yyy

